### ISSUE TITLE
Map not loading with Yoast SEO Premium

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#268]
Reported here - http://support.simplemap-plugin.com/discussions/problems/2796-map

When Yoast SEO Premium the map doesn't load and jQuery errors are output in the browser console.

**Comment by EkoJr** [comment]
Error Message

```
(index):394 Uncaught ReferenceError: load_simplemap is not defined
    at HTMLDocument.<anonymous> ((index):394)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
(anonymous) @ (index):394
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
```
Initial report

Error seems to occur because the PHP method `google_map_js_script` that contains the JS function `load_simplemap` isn't being executed. The WP hook `template_redirect` is what the PHP method would be hooked to.

I believe it could be part of Yoast's Redirect feature, but it also seems the (Yoast Redirect) configs are empty...but at the same time the .htaccess file seemed to have some configurations. Which seemed a bit odd.

**Comment by EkoJr** [comment]
This was triggered by a Advanced Setting in Yoast; which is also a setting not recommended to use.
