### ISSUE TITLE
Implement suggestions in email from Dave Iltis

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#27]
Implement suggestions in email from Dave Iltis <dave@cyclingutah.com> dated 02/05/2013

**Comment by michaeltorbert** [comment]
We should probably separate these suggestions into individual issues.

1. The individual location page map is awful!!
Here is an example of a better, but not ideal page:
cyclingutah.com/bike-shop/bingham-cyclery/
The map is 400x400 instead of 100x100. The smaller map is a complete waste. The larger map is better but not ideal. To make it ideal, you need to easily allow clicking on the map to open in a larger window. (Change this in the templates.php file). New code:
$return .= "<div class='sm-single-map'>[sm-location data='iframe-map' map_width='400px' map_height='400px']</div>";

I have also added in code to a 'Visit Website' link on the same page. Inexplicably, this is not included in SimpleMap.

(This can be fixed by adding:$return .= "<br /><a href=\"[sm-location data='url']\">Visit Website</a>";in the appropriate spot in the templates.php file.

I have also changed the wording on the 'Get Directions' to be Get Directions, Larger Map. Not ideal, but a workaround.
2. Please figure out how to make simplemap locations indexable by Google. Currently, it's not clear that they are (I don't think they are). This is a major problem for SEO.
3. User Roles. Currently, all wordpress user roles can add a new location. This is not ok. You need to have some sort of restriction to only allow admins and/or editors to add new locations. This is a major flaw.
4. On the main page, consider some possible changes:
When listing the locations, give the option of listing by category, not just distance from the user.
5. Consider (a larger project) adding a ratings and/or yelp like comment system to the locations so that. This is probably beyond the scope of this plugin, however.
6. There are reported fatal errors here http://wordpress.org/extend/plugins/simplemap/

**Comment by arnaudbroes** [comment]
@michaeltorbert Do you want me to add them all seperately? Just let me know and I'll do it in a bit.

**Comment by wpsmort** [comment]
I have broken this out into new issues - #55, #56, #58 and #59
