### ISSUE TITLE
Make SimpleMap mobile friendly

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#54]
Improve the display of the search form, map and location results so they are responsive.

Make phone numbers clickable so they dial the number on mobile devices.

**Comment by wpsmort** [comment]
This is done and tested with Twenty Fifteen, Twenty Sixteen and Twenty Seventeen themes.  

@michaeltorbert The responsive CSS is done in such a way that it should not break existing styling but we should make sure it's clearly stated in the changelog and update notification that we've added responsive styling and we should watch for issues reported in the forums.

**Comment by michaeltorbert** [comment]
@wpsmort  This looks much much better, in that it has a usable map. The problem is that the map is below a very large form so you have to scroll way down to get to it. I wonder if either moving the map to the top on small screens would be better, or maybe making the form smaller/responsive or making the form collapsible. 
<img width="937" alt="screen shot 2017-02-27 at 8 40 26 pm" src="https://cloud.githubusercontent.com/assets/17364998/23387870/200d68a2-fd2d-11e6-80d4-fce313f85a6c.png">
<img width="927" alt="screen shot 2017-02-27 at 8 40 57 pm" src="https://cloud.githubusercontent.com/assets/17364998/23387872/21c57e1e-fd2d-11e6-83ea-45d5293fc4b9.png">

**Comment by wpsmort** [comment]
We discussed this and agreed to push changes to the form to another release.  I've opened new issues #179 and #180 for this.
