### ISSUE TITLE
Fix widget / clean up widget options

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#7]
Fix widget / clean up widget options

**Comment by michaeltorbert** [comment]
@wpsmort @arnaudbroes  Any idea what we're wanting to do here?

**Comment by wpsmort** [comment]
@michaeltorbert This was something that Peter added to our old roadmap spreadsheet.  I don't recall why he added it as he didn't reference any customer issue.  I'd tasked Arnaud to copy what was in the old roadmap spreadsheet and create issues for each item.

We do have two separate issues (#151 and #140) open for PHP noticse in the widget.php file, I'm not aware of anything else that needs to be fixed with the widget.

As far as cleaning up options, I don't know that we need to make any changes and if we do then we should open individual issues for them as the request arise.

I am therefore going to close this issue.
